title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.764232
  brandStrength: 1
  lightness: 0.6256713
  brandColors:
    - '#8db5f0'
    - '#0d1015'
    - '#384b1d'
    - '#d0e0ed'
    - '#8ca34b'
  rhythmicContrast: 0.4172932
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ELESDEE
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1519871
layout_spectrum: 1
