name: ELESDEE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11723
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfbc8'
    - '#1c242f'
    - '#b1a374'
    - '#6e6137'
    - '#927e4c'
  brandStrength: 0.8125
  lightness: 0.41954306117258966
  saturation: 0.5317809502594173
  rhythmicContrast: 0.25
purpose: []
