name: ELESDEE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10278
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8db5f0'
    - '#0d1015'
    - '#384b1d'
    - '#d0e0ed'
    - '#8ca34b'
  brandStrength: 0.5
  lightness: 0.41954306117258966
  saturation: 0.5317809502594173
  rhythmicContrast: 0.25
purpose: []
