name: ELESDEE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10278
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5d8e9'
    - '#442218'
    - '#76503b'
    - '#e1a970'
    - '#d66c3a'
  brandStrength: 0.8125
  lightness: 0.41954306117258966
  saturation: 0.5317809502594173
  rhythmicContrast: 0.25
purpose: []
