title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5042965
  brandStrength: 0.7738991
  lightness: 0.5021482
  brandColors:
    - '#8db5f0'
    - '#0d1015'
    - '#384b1d'
    - '#d0e0ed'
    - '#8ca34b'
  rhythmicContrast: 0.5010741
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ELESDEE
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1455424
layout_spectrum: 1
